services:
  ome_origin:
    image: airensoft/ovenmediaengine:v0.19.0
    container_name: ome_origin
    restart: unless-stopped
    ports:
      - "1935:1935"               # RTMP
      - "3333:3333"               # WebRTC signaling (TCP)
      - "9999:9999/udp"           # WebRTC
      - "3478:3478"               # STUN/TURN (optional if using)
      - "9000:9000"               # OVT (Origin→Edge relay)
      - "10000-10009:10000-10009/udp"  # WebRTC media (SRTP)
    volumes:
      - ./configs/ome/OMEOriginServer.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml:ro

  stream_management:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: stream_management:local
    container_name: stream_management
    restart: unless-stopped
    ports:
      - "8080:8080" # grpc
      - "8081:8081" # http
    volumes:
      - ./configs/config.yaml:/app/config.yaml:ro