// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: cas.proto

package table

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayBackUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=tableId,proto3" json:"tableId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayBackUrlRequest) Reset() {
	*x = GetPlayBackUrlRequest{}
	mi := &file_cas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayBackUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayBackUrlRequest) ProtoMessage() {}

func (x *GetPlayBackUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayBackUrlRequest.ProtoReflect.Descriptor instead.
func (*GetPlayBackUrlRequest) Descriptor() ([]byte, []int) {
	return file_cas_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayBackUrlRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type GetPlayBackUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayBackUrl   string                 `protobuf:"bytes,1,opt,name=playBackUrl,proto3" json:"playBackUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayBackUrlResponse) Reset() {
	*x = GetPlayBackUrlResponse{}
	mi := &file_cas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayBackUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayBackUrlResponse) ProtoMessage() {}

func (x *GetPlayBackUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayBackUrlResponse.ProtoReflect.Descriptor instead.
func (*GetPlayBackUrlResponse) Descriptor() ([]byte, []int) {
	return file_cas_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayBackUrlResponse) GetPlayBackUrl() string {
	if x != nil {
		return x.PlayBackUrl
	}
	return ""
}

var File_cas_proto protoreflect.FileDescriptor

const file_cas_proto_rawDesc = "" +
	"\n" +
	"\tcas.proto\x12\x13cas.table.operation\"1\n" +
	"\x15GetPlayBackUrlRequest\x12\x18\n" +
	"\atableId\x18\x01 \x01(\tR\atableId\":\n" +
	"\x16GetPlayBackUrlResponse\x12 \n" +
	"\vplayBackUrl\x18\x01 \x01(\tR\vplayBackUrl2y\n" +
	"\fTableService\x12i\n" +
	"\x0eGetPlayBackUrl\x12*.cas.table.operation.GetPlayBackUrlRequest\x1a+.cas.table.operation.GetPlayBackUrlResponseB\xad\x01\n" +
	"\x17com.cas.table.operationB\bCasProtoP\x01Z\x1apkg/cas/api/v1/table;table\xa2\x02\x03CTO\xaa\x02\x13Cas.Table.Operation\xca\x02\x13Cas\\Table\\Operation\xe2\x02\x1fCas\\Table\\Operation\\GPBMetadata\xea\x02\x15Cas::Table::Operationb\x06proto3"

var (
	file_cas_proto_rawDescOnce sync.Once
	file_cas_proto_rawDescData []byte
)

func file_cas_proto_rawDescGZIP() []byte {
	file_cas_proto_rawDescOnce.Do(func() {
		file_cas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cas_proto_rawDesc), len(file_cas_proto_rawDesc)))
	})
	return file_cas_proto_rawDescData
}

var file_cas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cas_proto_goTypes = []any{
	(*GetPlayBackUrlRequest)(nil),  // 0: cas.table.operation.GetPlayBackUrlRequest
	(*GetPlayBackUrlResponse)(nil), // 1: cas.table.operation.GetPlayBackUrlResponse
}
var file_cas_proto_depIdxs = []int32{
	0, // 0: cas.table.operation.TableService.GetPlayBackUrl:input_type -> cas.table.operation.GetPlayBackUrlRequest
	1, // 1: cas.table.operation.TableService.GetPlayBackUrl:output_type -> cas.table.operation.GetPlayBackUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cas_proto_init() }
func file_cas_proto_init() {
	if File_cas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cas_proto_rawDesc), len(file_cas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cas_proto_goTypes,
		DependencyIndexes: file_cas_proto_depIdxs,
		MessageInfos:      file_cas_proto_msgTypes,
	}.Build()
	File_cas_proto = out.File
	file_cas_proto_goTypes = nil
	file_cas_proto_depIdxs = nil
}
