// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: webhooks.proto

package webhooks

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *ClientInfo            `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Request       *RequestInfo           `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionRequest) Reset() {
	*x = AdmissionRequest{}
	mi := &file_webhooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionRequest) ProtoMessage() {}

func (x *AdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionRequest.ProtoReflect.Descriptor instead.
func (*AdmissionRequest) Descriptor() ([]byte, []int) {
	return file_webhooks_proto_rawDescGZIP(), []int{0}
}

func (x *AdmissionRequest) GetClient() *ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AdmissionRequest) GetRequest() *RequestInfo {
	if x != nil {
		return x.Request
	}
	return nil
}

type AdmissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// required: true if request is allowed, false to reject.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// optional: URL to redirect the client (must match scheme, port, file).
	NewUrl string `protobuf:"bytes,2,opt,name=new_url,json=newUrl,proto3" json:"new_url,omitempty"`
	// optional: Connection lifetime in milliseconds. 0 means infinite.
	Lifetime uint64 `protobuf:"varint,3,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// optional: Reason for rejection or logging purposes.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionResponse) Reset() {
	*x = AdmissionResponse{}
	mi := &file_webhooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionResponse) ProtoMessage() {}

func (x *AdmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionResponse.ProtoReflect.Descriptor instead.
func (*AdmissionResponse) Descriptor() ([]byte, []int) {
	return file_webhooks_proto_rawDescGZIP(), []int{1}
}

func (x *AdmissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AdmissionResponse) GetNewUrl() string {
	if x != nil {
		return x.NewUrl
	}
	return ""
}

func (x *AdmissionResponse) GetLifetime() uint64 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

func (x *AdmissionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address of the client connected to the server
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Port number of the client
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// IP address forwarded by the proxy server
	RealIp        string `protobuf:"bytes,3,opt,name=real_ip,json=realIp,proto3" json:"real_ip,omitempty"`
	UserAgent     string `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"` // (Optional) Client's user-agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_webhooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_webhooks_proto_rawDescGZIP(), []int{2}
}

func (x *ClientInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClientInfo) GetRealIp() string {
	if x != nil {
		return x.RealIp
	}
	return ""
}

func (x *ClientInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// TODO RequestInfo: make direction, protocol, status as proto enum
type RequestInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// direction of the stream: incoming or outgoing
	Direction string `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	// protocol used: webrtc, rtmp, srt, llhls, thumbnail
	Protocol string `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// request status: opening or closing
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// original requested URL
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// (optional) redirected URL (used when closing)
	NewUrl string `protobuf:"bytes,5,opt,name=new_url,json=newUrl,proto3" json:"new_url,omitempty"`
	// time requested by the client (ISO8601 format)
	// TODO try to using proto Timestamp
	Time          string `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	mi := &file_webhooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_webhooks_proto_rawDescGZIP(), []int{3}
}

func (x *RequestInfo) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *RequestInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RequestInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RequestInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestInfo) GetNewUrl() string {
	if x != nil {
		return x.NewUrl
	}
	return ""
}

func (x *RequestInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_webhooks_proto protoreflect.FileDescriptor

const file_webhooks_proto_rawDesc = "" +
	"\n" +
	"\x0ewebhooks.proto\x12\"vortech.stream_management.webhooks\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\x10AdmissionRequest\x12N\n" +
	"\x06client\x18\x01 \x01(\v2..vortech.stream_management.webhooks.ClientInfoB\x06\xbaH\x03\xc8\x01\x01R\x06client\x12Q\n" +
	"\arequest\x18\x02 \x01(\v2/.vortech.stream_management.webhooks.RequestInfoB\x06\xbaH\x03\xc8\x01\x01R\arequest\"z\n" +
	"\x11AdmissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x17\n" +
	"\anew_url\x18\x02 \x01(\tR\x06newUrl\x12\x1a\n" +
	"\blifetime\x18\x03 \x01(\x04R\blifetime\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x91\x01\n" +
	"\n" +
	"ClientInfo\x12#\n" +
	"\aaddress\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01p\x01R\aaddress\x12\x1b\n" +
	"\x04port\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\x04port\x12\"\n" +
	"\areal_ip\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01p\x01R\x06realIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"\x8a\x02\n" +
	"\vRequestInfo\x127\n" +
	"\tdirection\x18\x01 \x01(\tB\x19\xbaH\x16r\x14R\bincomingR\boutgoingR\tdirection\x12F\n" +
	"\bprotocol\x18\x02 \x01(\tB*\xbaH'r%R\x06webrtcR\x04rtmpR\x03srtR\x05llhlsR\tthumbnailR\bprotocol\x12/\n" +
	"\x06status\x18\x03 \x01(\tB\x17\xbaH\x14r\x12R\aopeningR\aclosingR\x06status\x12\x1c\n" +
	"\x03url\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x88\x01\x01R\x03url\x12\x17\n" +
	"\anew_url\x18\x05 \x01(\tR\x06newUrl\x12\x12\n" +
	"\x04time\x18\x06 \x01(\tR\x04time2\x9f\x01\n" +
	"\bWebhooks\x12\x92\x01\n" +
	"\tAdmission\x124.vortech.stream_management.webhooks.AdmissionRequest\x1a5.vortech.stream_management.webhooks.AdmissionResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/admissionB\xf7\x01\n" +
	"&com.vortech.stream_management.webhooksB\rWebhooksProtoP\x01Z\x18api/v1/webhooks;webhooks\xa2\x02\x03VSW\xaa\x02!Vortech.StreamManagement.Webhooks\xca\x02!Vortech\\StreamManagement\\Webhooks\xe2\x02-Vortech\\StreamManagement\\Webhooks\\GPBMetadata\xea\x02#Vortech::StreamManagement::Webhooksb\x06proto3"

var (
	file_webhooks_proto_rawDescOnce sync.Once
	file_webhooks_proto_rawDescData []byte
)

func file_webhooks_proto_rawDescGZIP() []byte {
	file_webhooks_proto_rawDescOnce.Do(func() {
		file_webhooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhooks_proto_rawDesc), len(file_webhooks_proto_rawDesc)))
	})
	return file_webhooks_proto_rawDescData
}

var file_webhooks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_webhooks_proto_goTypes = []any{
	(*AdmissionRequest)(nil),  // 0: vortech.stream_management.webhooks.AdmissionRequest
	(*AdmissionResponse)(nil), // 1: vortech.stream_management.webhooks.AdmissionResponse
	(*ClientInfo)(nil),        // 2: vortech.stream_management.webhooks.ClientInfo
	(*RequestInfo)(nil),       // 3: vortech.stream_management.webhooks.RequestInfo
}
var file_webhooks_proto_depIdxs = []int32{
	2, // 0: vortech.stream_management.webhooks.AdmissionRequest.client:type_name -> vortech.stream_management.webhooks.ClientInfo
	3, // 1: vortech.stream_management.webhooks.AdmissionRequest.request:type_name -> vortech.stream_management.webhooks.RequestInfo
	0, // 2: vortech.stream_management.webhooks.Webhooks.Admission:input_type -> vortech.stream_management.webhooks.AdmissionRequest
	1, // 3: vortech.stream_management.webhooks.Webhooks.Admission:output_type -> vortech.stream_management.webhooks.AdmissionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webhooks_proto_init() }
func file_webhooks_proto_init() {
	if File_webhooks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhooks_proto_rawDesc), len(file_webhooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhooks_proto_goTypes,
		DependencyIndexes: file_webhooks_proto_depIdxs,
		MessageInfos:      file_webhooks_proto_msgTypes,
	}.Build()
	File_webhooks_proto = out.File
	file_webhooks_proto_goTypes = nil
	file_webhooks_proto_depIdxs = nil
}
