// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: management.proto

package management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Management_GetPlaybackUrl_FullMethodName    = "/vortech.stream_management.management.Management/GetPlaybackUrl"
	Management_ExtendStreamToken_FullMethodName = "/vortech.stream_management.management.Management/ExtendStreamToken"
	Management_RevokeStreamToken_FullMethodName = "/vortech.stream_management.management.Management/RevokeStreamToken"
)

// ManagementClient is the client API for Management service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// For internal, service to service
type ManagementClient interface {
	GetPlaybackUrl(ctx context.Context, in *GetPlaybackUrlRequest, opts ...grpc.CallOption) (*GetPlaybackUrlResponse, error)
	ExtendStreamToken(ctx context.Context, in *ExtendStreamTokenRequest, opts ...grpc.CallOption) (*ExtendStreamTokenResponse, error)
	RevokeStreamToken(ctx context.Context, in *RevokeStreamTokenRequest, opts ...grpc.CallOption) (*RevokeStreamTokenResponse, error)
}

type managementClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementClient(cc grpc.ClientConnInterface) ManagementClient {
	return &managementClient{cc}
}

func (c *managementClient) GetPlaybackUrl(ctx context.Context, in *GetPlaybackUrlRequest, opts ...grpc.CallOption) (*GetPlaybackUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaybackUrlResponse)
	err := c.cc.Invoke(ctx, Management_GetPlaybackUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementClient) ExtendStreamToken(ctx context.Context, in *ExtendStreamTokenRequest, opts ...grpc.CallOption) (*ExtendStreamTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendStreamTokenResponse)
	err := c.cc.Invoke(ctx, Management_ExtendStreamToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementClient) RevokeStreamToken(ctx context.Context, in *RevokeStreamTokenRequest, opts ...grpc.CallOption) (*RevokeStreamTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeStreamTokenResponse)
	err := c.cc.Invoke(ctx, Management_RevokeStreamToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServer is the server API for Management service.
// All implementations must embed UnimplementedManagementServer
// for forward compatibility.
//
// For internal, service to service
type ManagementServer interface {
	GetPlaybackUrl(context.Context, *GetPlaybackUrlRequest) (*GetPlaybackUrlResponse, error)
	ExtendStreamToken(context.Context, *ExtendStreamTokenRequest) (*ExtendStreamTokenResponse, error)
	RevokeStreamToken(context.Context, *RevokeStreamTokenRequest) (*RevokeStreamTokenResponse, error)
	mustEmbedUnimplementedManagementServer()
}

// UnimplementedManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServer struct{}

func (UnimplementedManagementServer) GetPlaybackUrl(context.Context, *GetPlaybackUrlRequest) (*GetPlaybackUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaybackUrl not implemented")
}
func (UnimplementedManagementServer) ExtendStreamToken(context.Context, *ExtendStreamTokenRequest) (*ExtendStreamTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendStreamToken not implemented")
}
func (UnimplementedManagementServer) RevokeStreamToken(context.Context, *RevokeStreamTokenRequest) (*RevokeStreamTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeStreamToken not implemented")
}
func (UnimplementedManagementServer) mustEmbedUnimplementedManagementServer() {}
func (UnimplementedManagementServer) testEmbeddedByValue()                    {}

// UnsafeManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServer will
// result in compilation errors.
type UnsafeManagementServer interface {
	mustEmbedUnimplementedManagementServer()
}

func RegisterManagementServer(s grpc.ServiceRegistrar, srv ManagementServer) {
	// If the following call pancis, it indicates UnimplementedManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Management_ServiceDesc, srv)
}

func _Management_GetPlaybackUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaybackUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).GetPlaybackUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Management_GetPlaybackUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).GetPlaybackUrl(ctx, req.(*GetPlaybackUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Management_ExtendStreamToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendStreamTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).ExtendStreamToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Management_ExtendStreamToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).ExtendStreamToken(ctx, req.(*ExtendStreamTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Management_RevokeStreamToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeStreamTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).RevokeStreamToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Management_RevokeStreamToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).RevokeStreamToken(ctx, req.(*RevokeStreamTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Management_ServiceDesc is the grpc.ServiceDesc for Management service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Management_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vortech.stream_management.management.Management",
	HandlerType: (*ManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlaybackUrl",
			Handler:    _Management_GetPlaybackUrl_Handler,
		},
		{
			MethodName: "ExtendStreamToken",
			Handler:    _Management_ExtendStreamToken_Handler,
		},
		{
			MethodName: "RevokeStreamToken",
			Handler:    _Management_RevokeStreamToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management.proto",
}
