grpc_listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

http_listener:
  tcp:
    address: 0.0.0.0
    port: 8081
    secure: false

logger:
  pretty: true
  level: DEBUG

authorization:
  enabled: true
  secret_key: my_secret_key # TODO setup in Vault

stream_token:
  enabled: true

cas_table:
  enabled: true
  socket:
    address: localhost
    port: 8080
    secure: false