grpc_listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

http_listener:
  tcp:
    address: 0.0.0.0
    port: 8081
    secure: false

logger:
  pretty: false
  level: DEBUG

authorization:
  enabled: true
  # TODO setup in Vault/SecretManager
  secret_key: mLwmcZMbhiZfCJiIsMwcslzE55IwmUBG

stream_token:
  enabled: true
  jwt_signing:
    # TODO setup in Vault/SecretManager
    private_key:
    issuer: stream_management
    default_audience: my_ome
    expires_time: 120000 # 2 minutes in milliseconds

cas_table:
  enabled: false
  socket:
    address: localhost
    port: 8080
    secure: false
  noop_default_playback_url: ws://localhost:3333/app/baccarat