grpc_listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

http_listener:
  tcp:
    address: 0.0.0.0
    port: 8081
    secure: false

logger:
  pretty: true
  level: DEBUG

cas_table:
  address: localhost
  port: 8080
  secure: false